Repository canonical/checkbox, pull requests merged in 2024-09, with the labels that each got.

#1439 [checkbox-ce-oem] add test cases to validate those plug and slot interface defined in gadget snap (New)
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/check_gadget_interface.py
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/gadget_interface_utils.py
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/data/gadget_interface_schema.json
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/jobs.pxu
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/manifest.pxu
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/test-plan.pxu
Labels: ce-oem

#1444 fix black format issue (Bugfix)
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/gadget_interface_utils.py
Labels: ce-oem

#1204 Update possible certification status values for Job units and modify its default (new)
  checkbox-ng/checkbox_ng/launcher/merge_reports.py
  checkbox-ng/checkbox_ng/launcher/subcommands.py
  checkbox-ng/checkbox_ng/launcher/test_merge_reports.py
  checkbox-ng/checkbox_ng/launcher/test_subcommands.py
  checkbox-ng/plainbox/impl/exporter/test_html.py
  checkbox-ng/plainbox/impl/exporter/test_init.py
  checkbox-ng/plainbox/impl/exporter/test_xlsx.py
  checkbox-ng/plainbox/impl/exporter/xlsx.py
  checkbox-ng/plainbox/impl/providers/exporters/data/checkbox.html
  checkbox-ng/plainbox/impl/providers/exporters/data/global.txt
  checkbox-ng/plainbox/impl/providers/exporters/data/multi-page.html
  checkbox-ng/plainbox/impl/unit/job.py
  checkbox-ng/plainbox/test-data/html-exporter/with_both_certification_status.html
  checkbox-ng/plainbox/test-data/html-exporter/with_certification_non_blocker.html
  docs/how-to/nested-test-plan.rst
  docs/reference/units/job.rst
  docs/tutorial/using-checkbox/generate-report.rst
  submission-schema/schema.json
Labels: waiting-for-changes

#1445 [checkbox-ce-oem] Fix all checks in ceoem (Bugfix)
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/performance_mode_controller.py
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/rpmsg_load_firmware.py
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/spidev_test.py
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/tests/test_cpufreq_governors.py
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/tests/test_gst_v4l2_video_decoder_md5_checksum_comparison.py
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/tests/test_rpmsg_load_firmware.py
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/tests/test_rpmsg_tests.py
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/tests/test_tcp_multi_connections.py
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/jobs.pxu
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/optee/jobs.pxu
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/strict-confinement/test-plan-strict-confinement.pxu
Labels: ce-oem

#1342 restructure the setup and teardown functions for network.py scripts (Bugfix)
  providers/base/bin/network.py
  providers/base/tests/test_network.py
Labels: waiting-for-changes

#1206 Add cert-blocker status based on coverage guide for IoT test plans (BugFix)
  providers/base/units/audio/test-plan.pxu
  providers/base/units/bluetooth/test-plan.pxu
  providers/base/units/ethernet/test-plan.pxu
  providers/base/units/i2c/test-plan.pxu
  providers/base/units/led/test-plan.pxu
  providers/base/units/memory/test-plan.pxu
  providers/base/units/monitor/test-plan.pxu
  providers/base/units/power-management/test-plan.pxu
  providers/base/units/rtc/test-plan.pxu
  providers/base/units/serial/test-plan.pxu
  providers/base/units/usb/test-plan.pxu
  providers/base/units/wireless/test-plan.pxu
  providers/base/units/wwan/test-plan.pxu
  providers/certification-client/units/client-cert-iot-desktop-24-04.pxu
  providers/certification-client/units/client-cert-iot-server-16-04.pxu
  providers/certification-client/units/client-cert-iot-server-18-04.pxu
  providers/certification-client/units/client-cert-iot-server-20-04.pxu
  providers/certification-client/units/client-cert-iot-server-22-04.pxu
  providers/certification-client/units/client-cert-iot-server-24-04.pxu
  providers/certification-client/units/client-cert-iot-ubuntucore-16.pxu
  providers/certification-client/units/client-cert-iot-ubuntucore-18.pxu
  providers/certification-client/units/client-cert-iot-ubuntucore-20.pxu
  providers/certification-client/units/client-cert-iot-ubuntucore-22.pxu
  providers/certification-client/units/client-cert-iot-ubuntucore-24.pxu
  providers/tpm2/units/test-plan.pxu
Labels: waiting-for-changes

#1451 Sd card not tested (BugFix)
  checkbox-support/checkbox_support/parsers/tests/test_udevadm.py
  checkbox-support/checkbox_support/parsers/tests/udevadm_data/XILINX_KR260.lsblk
  checkbox-support/checkbox_support/parsers/tests/udevadm_data/XILINX_KR260.txt
  checkbox-support/checkbox_support/parsers/udevadm.py
  providers/base/bin/disk_read_performance_test.sh
  providers/base/bin/storage_test.py
  providers/base/tests/test_storage_test.py
  providers/base/units/benchmarks/jobs.pxu
  providers/base/units/disk/test-plan.pxu
Labels: waiting-for-changes

#1494 Update gadget interface validation test plan (BugFix)
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/jobs.pxu
  contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/test-plan-ce-oem.pxu
Labels: ce-oem

#1498 Fix the combination of backup_loc path (Bugfix)
  providers/base/bin/wifi_nmcli_backup.py
Labels: bug, Importance: Critical

#1515 Correct the camera job cmd with right camera tests (Bugfix)
  providers/base/units/camera/jobs.pxu
Labels: bug, Importance: Critical
